# experiment parameters
exp_params:
    dataset: fixed
    num_steps: 2
    num_tests: 100
    model_type: sequential
    activation: tanh
    random_seed: 2023


# training parameters
train_params:
    batch_size: 1
    steps_per_epoch: 1
    epochs: 10000


# parameters for optimization algorithms
algos:
    Algorithm1: {learning_rate: 1.0e-1}
    Algorithm2: {learning_rate: 3.0e-2}
    Algorithm3: {learning_rate: 1.0e-2}
    Algorithm4: {learning_rate: 3.0e-3}
    Algorithm5: {learning_rate: 1.0e-3}
    Algorithm6: {learning_rate: 3.0e-4}
    Algorithm7: {learning_rate: 1.0e-4}

